version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      everything:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"