spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.profiles.default=dev
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.servlet.context-path=/api
server.forward-headers-strategy=framework
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
