spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.profiles.default=dev
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
springdoc.use-management-port=false