spring.profiles.default=dev
springdoc.api-docs.path=/api/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/api/v3/api-docs
springdoc.swagger-ui.config-url=/api/v3/api-docs/swagger-config
springdoc.use-management-port=false
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.jackson.deserialization.fail-on-null-for-primitives=false